name: Build success/failure notification action

on:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
  notify:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Success
      
        if: ${{ success() }}
        uses: tenzin1308/discord-notification@v1.0.0
        with:
          discord-webhook-url: ${{ secrets.WEBHOOKS_URL }} 

      - name: Failure
        if: ${{ failure() }}
        uses: tenzin1308/discord-notification@v1.0.0
        with:
         discord-webhook-url: ${{ secrets.WEBHOOKS_URL }}
